#ifndef _SUSI_IMC_VCIL_API_H
#define _SUSI_IMC_VCIL_API_H

DLLAPI USHORT SUSI_IMC_VCIL_Initialize (IN UCHAR can_bus_number);
DLLAPI USHORT SUSI_IMC_VCIL_Deinitialize (IN UCHAR can_bus_number);
DLLAPI USHORT SUSI_IMC_VCIL_GetLibVersion ( OUT char *version );
DLLAPI USHORT SUSI_IMC_VCIL_GetFWVersion ( OUT char* version );
DLLAPI USHORT SUSI_IMC_VCIL_ResetModule ( void );
DLLAPI USHORT SUSI_IMC_VCIL_ModuleControl ( IN VCIL_CAN_CHANNEL_MODE port1, IN VCIL_CAN_CHANNEL_MODE port2);
DLLAPI USHORT SUSI_IMC_VCIL_ModuleControl_Port1 ( IN VCIL_CAN_CHANNEL_MODE port);
DLLAPI USHORT SUSI_IMC_VCIL_ModuleControl_Port2 ( IN VCIL_CAN_CHANNEL_MODE port);
#endif
