#ifndef _VCIL_CMD_H
#define _VCIL_CMD_H

#include "SUSI_IMC_Types.h"
#include <list>
#include <pthread.h>
#include <semaphore.h>

using namespace std;

enum SUSI_API_CMD
{
	SUSI_API_CMD_VCIL_INITIALIZE = 0,
	SUSI_API_CMD_VCIL_DEINITIALIZE,
	SUSI_API_CMD_VCIL_GET_LIB_VERSION,
	SUSI_API_CMD_VCIL_GET_FIRMWARE_VERSION,
	SUSI_API_CMD_VCIL_RESET_MODULE,
	SUSI_API_CMD_VCIL_MODULE_CONTROL,
	SUSI_API_CMD_CAN_SET_BIT_TIMING,
	SUSI_API_CMD_CAN_SET_BIT_TIMING_SILENCE,
	SUSI_API_CMD_CAN_GET_BIT_TIMING,
	SUSI_API_CMD_CAN_SET_MESSAGE_MASK,
	SUSI_API_CMD_CAN_GET_MESSAGE_MASK,
	SUSI_API_CMD_CAN_REMOVE_MESSAGE_MASK,
	SUSI_API_CMD_CAN_RESET_MESSAGE_MASK,
	SUSI_API_CMD_CAN_READ,
	SUSI_API_CMD_CAN_WRITE,
	SUSI_API_CMD_CAN_GET_BUS_ERROR_STATUS,
	SUSI_API_CMD_CAN_SET_EVENT,
	SUSI_API_CMD_J1708_READ,
	SUSI_API_CMD_J1708_WRITE,
	SUSI_API_CMD_J1708_SET_EVENT,
	SUSI_API_CMD_J1708_ADD_MESSAGE_FILTER,
	SUSI_API_CMD_J1708_GET_MESSAGE_FILTER,
	SUSI_API_CMD_J1708_REMOVE_MESSAGE_FILTER,
	SUSI_API_CMD_J1708_REMOVE_ALL_MESSAGE_FILTER,
	SUSI_API_CMD_J1939_READ,
	SUSI_API_CMD_J1939_WRITE,
	SUSI_API_CMD_J1939_SET_EVENT,
	SUSI_API_CMD_J1939_ADD_MESSAGE_FILTER,
	SUSI_API_CMD_J1939_GET_MESSAGE_FILTER,
	SUSI_API_CMD_J1939_REMOVE_MESSAGE_FILTER,
	SUSI_API_CMD_J1939_REMOVE_ALL_MESSAGE_FILTER,
	SUSI_API_CMD_J1939_SET_ADDRESS_AND_NAME,
	SUSI_API_CMD_J1939_GET_ADDRESS_AND_NAME,
	SUSI_API_CMD_J1587_READ,
	SUSI_API_CMD_J1587_WRITE,
	SUSI_API_CMD_J1587_SET_EVENT,
	SUSI_API_CMD_J1587_ADD_MESSAGE_FILTER,
	SUSI_API_CMD_J1587_GET_MESSAGE_FILTER,
	SUSI_API_CMD_J1587_REMOVE_MESSAGE_FILTER,
	SUSI_API_CMD_J1587_REMOVE_ALL_MESSAGE_FILTER,
	SUSI_API_CMD_OBD2_READ,
	SUSI_API_CMD_OBD2_WRITE,
	SUSI_API_CMD_OBD2_SET_EVENT,
	SUSI_API_CMD_OBD2_ADD_MESSAGE_FILTER,
	SUSI_API_CMD_OBD2_GET_MESSAGE_FILTER,
	SUSI_API_CMD_OBD2_REMOVE_MESSAGE_FILTER,
	SUSI_API_CMD_OBD2_REMOVE_ALL_MESSAGE_FILTER
};

enum SUSI_CMD_GROUP
{
	CMD_GROUP_VCIL = 0,
	CMD_GROUP_CAN,
	CMD_GROUP_J1708,
	CMD_GROUP_J1939,
	CMD_GROUP_J1587,
	CMD_GROUP_OBD2
};

class SUSICommand
{
public:
	SUSICommand(SUSI_API_CMD cmd);
	~SUSICommand();

	SUSI_API_CMD susi_cmd;
    
    //pthread_cond_t ret_event;
    //pthread_mutex_t ret_event_mutex;    
    sem_t ret_sem;
    
	int		cmd_group;
    bool    execute_done;

	USHORT	result;

	list <void*> input_parameter;
	
	void Done(USHORT ret_val);
};

#endif

