// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#ifndef _Localization_Msg_h
#define _Localization_Msg_h

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _Localization_Msg Localization_Msg;
struct _Localization_Msg
{
    int16_t    version;
    int16_t    RealSensorCount;
    float      StartAngle[4];
    float      EndAngle[4];
    int16_t    LaserCount[4];
    float      InstallPos_X[4];
    float      InstallPos_Y[4];
    float      InstallPos_Thita[4];
    int16_t    VisualRange[4];
    float      VisualAngleStart[4];
    float      VisualAngleEnd[4];
    int16_t    timestamp_start;
    int16_t    timestamp_vel;
    int16_t    timestamp_data[4];
    int16_t    laser_id;
    int16_t    lenth;
    int16_t    *distance;
    int16_t    *intensity;
    float      position[3];
    float      vel[3];
};

Localization_Msg   *Localization_Msg_copy(const Localization_Msg *p);
void Localization_Msg_destroy(Localization_Msg *p);

typedef struct _Localization_Msg_subscription_t Localization_Msg_subscription_t;
typedef void(*Localization_Msg_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const Localization_Msg *msg, void *user);

int Localization_Msg_publish(lcm_t *lcm, const char *channel, const Localization_Msg *p);
Localization_Msg_subscription_t* Localization_Msg_subscribe(lcm_t *lcm, const char *channel, Localization_Msg_handler_t f, void *userdata);
int Localization_Msg_unsubscribe(lcm_t *lcm, Localization_Msg_subscription_t* hid);
int Localization_Msg_subscription_set_queue_capacity(Localization_Msg_subscription_t* subs,
                              int num_messages);


int  Localization_Msg_encode(void *buf, int offset, int maxlen, const Localization_Msg *p);
int  Localization_Msg_decode(const void *buf, int offset, int maxlen, Localization_Msg *p);
int  Localization_Msg_decode_cleanup(Localization_Msg *p);
int  Localization_Msg_encoded_size(const Localization_Msg *p);

// LCM support functions. Users should not call these
int64_t __Localization_Msg_get_hash(void);
int64_t __Localization_Msg_hash_recursive(const __lcm_hash_ptr *p);
int     __Localization_Msg_encode_array(void *buf, int offset, int maxlen, const Localization_Msg *p, int elements);
int     __Localization_Msg_decode_array(const void *buf, int offset, int maxlen, Localization_Msg *p, int elements);
int     __Localization_Msg_decode_array_cleanup(Localization_Msg *p, int elements);
int     __Localization_Msg_encoded_array_size(const Localization_Msg *p, int elements);
int     __Localization_Msg_clone_array(const Localization_Msg *p, Localization_Msg *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
