// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "LocalizationTest_Msg.h"

static int __LocalizationTest_Msg_hash_computed;
static uint64_t __LocalizationTest_Msg_hash;

uint64_t __LocalizationTest_Msg_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __LocalizationTest_Msg_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __LocalizationTest_Msg_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x420169715bfb40ebLL
         + __int8_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __LocalizationTest_Msg_get_hash(void)
{
    if (!__LocalizationTest_Msg_hash_computed) {
        __LocalizationTest_Msg_hash = (int64_t)__LocalizationTest_Msg_hash_recursive(NULL);
        __LocalizationTest_Msg_hash_computed = 1;
    }

    return __LocalizationTest_Msg_hash;
}

int __LocalizationTest_Msg_encode_array(void *buf, int offset, int maxlen, const LocalizationTest_Msg *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].version), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RealSensorCount), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].position, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].dis, p[element].RealSensorCount);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int LocalizationTest_Msg_encode(void *buf, int offset, int maxlen, const LocalizationTest_Msg *p)
{
    int pos = 0, thislen;
    int64_t hash = __LocalizationTest_Msg_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __LocalizationTest_Msg_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __LocalizationTest_Msg_encoded_array_size(const LocalizationTest_Msg *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int8_t_encoded_array_size(&(p[element].version), 1);

        size += __int8_t_encoded_array_size(&(p[element].RealSensorCount), 1);

        size += __float_encoded_array_size(p[element].position, 3);

        size += __float_encoded_array_size(p[element].vel, 3);

        size += __int16_t_encoded_array_size(p[element].dis, p[element].RealSensorCount);

    }
    return size;
}

int LocalizationTest_Msg_encoded_size(const LocalizationTest_Msg *p)
{
    return 8 + __LocalizationTest_Msg_encoded_array_size(p, 1);
}

int __LocalizationTest_Msg_decode_array(const void *buf, int offset, int maxlen, LocalizationTest_Msg *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].version), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RealSensorCount), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].position, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].dis = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].RealSensorCount);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].dis, p[element].RealSensorCount);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __LocalizationTest_Msg_decode_array_cleanup(LocalizationTest_Msg *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_decode_array_cleanup(&(p[element].version), 1);

        __int8_t_decode_array_cleanup(&(p[element].RealSensorCount), 1);

        __float_decode_array_cleanup(p[element].position, 3);

        __float_decode_array_cleanup(p[element].vel, 3);

        __int16_t_decode_array_cleanup(p[element].dis, p[element].RealSensorCount);
        if (p[element].dis) free(p[element].dis);

    }
    return 0;
}

int LocalizationTest_Msg_decode(const void *buf, int offset, int maxlen, LocalizationTest_Msg *p)
{
    int pos = 0, thislen;
    int64_t hash = __LocalizationTest_Msg_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __LocalizationTest_Msg_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LocalizationTest_Msg_decode_cleanup(LocalizationTest_Msg *p)
{
    return __LocalizationTest_Msg_decode_array_cleanup(p, 1);
}

int __LocalizationTest_Msg_clone_array(const LocalizationTest_Msg *p, LocalizationTest_Msg *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int8_t_clone_array(&(p[element].version), &(q[element].version), 1);

        __int8_t_clone_array(&(p[element].RealSensorCount), &(q[element].RealSensorCount), 1);

        __float_clone_array(p[element].position, q[element].position, 3);

        __float_clone_array(p[element].vel, q[element].vel, 3);

        q[element].dis = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].RealSensorCount);
        __int16_t_clone_array(p[element].dis, q[element].dis, p[element].RealSensorCount);

    }
    return 0;
}

LocalizationTest_Msg *LocalizationTest_Msg_copy(const LocalizationTest_Msg *p)
{
    LocalizationTest_Msg *q = (LocalizationTest_Msg*) malloc(sizeof(LocalizationTest_Msg));
    __LocalizationTest_Msg_clone_array(p, q, 1);
    return q;
}

void LocalizationTest_Msg_destroy(LocalizationTest_Msg *p)
{
    __LocalizationTest_Msg_decode_array_cleanup(p, 1);
    free(p);
}

int LocalizationTest_Msg_publish(lcm_t *lc, const char *channel, const LocalizationTest_Msg *p)
{
      int max_data_size = LocalizationTest_Msg_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = LocalizationTest_Msg_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _LocalizationTest_Msg_subscription_t {
    LocalizationTest_Msg_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void LocalizationTest_Msg_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    LocalizationTest_Msg p;
    memset(&p, 0, sizeof(LocalizationTest_Msg));
    status = LocalizationTest_Msg_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding LocalizationTest_Msg!!!\n", status);
        return;
    }

    LocalizationTest_Msg_subscription_t *h = (LocalizationTest_Msg_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    LocalizationTest_Msg_decode_cleanup (&p);
}

LocalizationTest_Msg_subscription_t* LocalizationTest_Msg_subscribe (lcm_t *lcm,
                    const char *channel,
                    LocalizationTest_Msg_handler_t f, void *userdata)
{
    LocalizationTest_Msg_subscription_t *n = (LocalizationTest_Msg_subscription_t*)
                       malloc(sizeof(LocalizationTest_Msg_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 LocalizationTest_Msg_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg LocalizationTest_Msg LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int LocalizationTest_Msg_subscription_set_queue_capacity (LocalizationTest_Msg_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int LocalizationTest_Msg_unsubscribe(lcm_t *lcm, LocalizationTest_Msg_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe LocalizationTest_Msg_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

