// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "Localization_Msg.h"

static int __Localization_Msg_hash_computed;
static int64_t __Localization_Msg_hash;

int64_t __Localization_Msg_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __Localization_Msg_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__Localization_Msg_get_hash };
    (void) cp;

    int64_t hash = 0x9fc4abafcb4dd335LL
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __int16_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __Localization_Msg_get_hash(void)
{
    if (!__Localization_Msg_hash_computed) {
        __Localization_Msg_hash = __Localization_Msg_hash_recursive(NULL);
        __Localization_Msg_hash_computed = 1;
    }

    return __Localization_Msg_hash;
}

int __Localization_Msg_encode_array(void *buf, int offset, int maxlen, const Localization_Msg *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].version), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].RealSensorCount), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].StartAngle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].EndAngle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].LaserCount, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].InstallPos_X, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].InstallPos_Y, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].InstallPos_Thita, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].VisualRange, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].VisualAngleStart, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].VisualAngleEnd, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp_start), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].timestamp_data, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].laser_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].lenth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].distance, p[element].lenth);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, p[element].intensity, p[element].lenth);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].position, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int Localization_Msg_encode(void *buf, int offset, int maxlen, const Localization_Msg *p)
{
    int pos = 0, thislen;
    int64_t hash = __Localization_Msg_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __Localization_Msg_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __Localization_Msg_encoded_array_size(const Localization_Msg *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int16_t_encoded_array_size(&(p[element].version), 1);

        size += __int16_t_encoded_array_size(&(p[element].RealSensorCount), 1);

        size += __float_encoded_array_size(p[element].StartAngle, 4);

        size += __float_encoded_array_size(p[element].EndAngle, 4);

        size += __int16_t_encoded_array_size(p[element].LaserCount, 4);

        size += __float_encoded_array_size(p[element].InstallPos_X, 4);

        size += __float_encoded_array_size(p[element].InstallPos_Y, 4);

        size += __float_encoded_array_size(p[element].InstallPos_Thita, 4);

        size += __int16_t_encoded_array_size(p[element].VisualRange, 4);

        size += __float_encoded_array_size(p[element].VisualAngleStart, 4);

        size += __float_encoded_array_size(p[element].VisualAngleEnd, 4);

        size += __int16_t_encoded_array_size(&(p[element].timestamp_start), 1);

        size += __int16_t_encoded_array_size(&(p[element].timestamp_vel), 1);

        size += __int16_t_encoded_array_size(p[element].timestamp_data, 4);

        size += __int16_t_encoded_array_size(&(p[element].laser_id), 1);

        size += __int16_t_encoded_array_size(&(p[element].lenth), 1);

        size += __int16_t_encoded_array_size(p[element].distance, p[element].lenth);

        size += __int16_t_encoded_array_size(p[element].intensity, p[element].lenth);

        size += __float_encoded_array_size(p[element].position, 3);

        size += __float_encoded_array_size(p[element].vel, 3);

    }
    return size;
}

int Localization_Msg_encoded_size(const Localization_Msg *p)
{
    return 8 + __Localization_Msg_encoded_array_size(p, 1);
}

int __Localization_Msg_decode_array(const void *buf, int offset, int maxlen, Localization_Msg *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].version), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].RealSensorCount), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].StartAngle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].EndAngle, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].LaserCount, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].InstallPos_X, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].InstallPos_Y, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].InstallPos_Thita, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].VisualRange, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].VisualAngleStart, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].VisualAngleEnd, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp_start), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp_vel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].timestamp_data, 4);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].laser_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].lenth), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].distance = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].lenth);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].distance, p[element].lenth);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].intensity = (int16_t*) lcm_malloc(sizeof(int16_t) * p[element].lenth);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, p[element].intensity, p[element].lenth);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].position, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __Localization_Msg_decode_array_cleanup(Localization_Msg *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_decode_array_cleanup(&(p[element].version), 1);

        __int16_t_decode_array_cleanup(&(p[element].RealSensorCount), 1);

        __float_decode_array_cleanup(p[element].StartAngle, 4);

        __float_decode_array_cleanup(p[element].EndAngle, 4);

        __int16_t_decode_array_cleanup(p[element].LaserCount, 4);

        __float_decode_array_cleanup(p[element].InstallPos_X, 4);

        __float_decode_array_cleanup(p[element].InstallPos_Y, 4);

        __float_decode_array_cleanup(p[element].InstallPos_Thita, 4);

        __int16_t_decode_array_cleanup(p[element].VisualRange, 4);

        __float_decode_array_cleanup(p[element].VisualAngleStart, 4);

        __float_decode_array_cleanup(p[element].VisualAngleEnd, 4);

        __int16_t_decode_array_cleanup(&(p[element].timestamp_start), 1);

        __int16_t_decode_array_cleanup(&(p[element].timestamp_vel), 1);

        __int16_t_decode_array_cleanup(p[element].timestamp_data, 4);

        __int16_t_decode_array_cleanup(&(p[element].laser_id), 1);

        __int16_t_decode_array_cleanup(&(p[element].lenth), 1);

        __int16_t_decode_array_cleanup(p[element].distance, p[element].lenth);
        if (p[element].distance) free(p[element].distance);

        __int16_t_decode_array_cleanup(p[element].intensity, p[element].lenth);
        if (p[element].intensity) free(p[element].intensity);

        __float_decode_array_cleanup(p[element].position, 3);

        __float_decode_array_cleanup(p[element].vel, 3);

    }
    return 0;
}

int Localization_Msg_decode(const void *buf, int offset, int maxlen, Localization_Msg *p)
{
    int pos = 0, thislen;
    int64_t hash = __Localization_Msg_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __Localization_Msg_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int Localization_Msg_decode_cleanup(Localization_Msg *p)
{
    return __Localization_Msg_decode_array_cleanup(p, 1);
}

int __Localization_Msg_clone_array(const Localization_Msg *p, Localization_Msg *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int16_t_clone_array(&(p[element].version), &(q[element].version), 1);

        __int16_t_clone_array(&(p[element].RealSensorCount), &(q[element].RealSensorCount), 1);

        __float_clone_array(p[element].StartAngle, q[element].StartAngle, 4);

        __float_clone_array(p[element].EndAngle, q[element].EndAngle, 4);

        __int16_t_clone_array(p[element].LaserCount, q[element].LaserCount, 4);

        __float_clone_array(p[element].InstallPos_X, q[element].InstallPos_X, 4);

        __float_clone_array(p[element].InstallPos_Y, q[element].InstallPos_Y, 4);

        __float_clone_array(p[element].InstallPos_Thita, q[element].InstallPos_Thita, 4);

        __int16_t_clone_array(p[element].VisualRange, q[element].VisualRange, 4);

        __float_clone_array(p[element].VisualAngleStart, q[element].VisualAngleStart, 4);

        __float_clone_array(p[element].VisualAngleEnd, q[element].VisualAngleEnd, 4);

        __int16_t_clone_array(&(p[element].timestamp_start), &(q[element].timestamp_start), 1);

        __int16_t_clone_array(&(p[element].timestamp_vel), &(q[element].timestamp_vel), 1);

        __int16_t_clone_array(p[element].timestamp_data, q[element].timestamp_data, 4);

        __int16_t_clone_array(&(p[element].laser_id), &(q[element].laser_id), 1);

        __int16_t_clone_array(&(p[element].lenth), &(q[element].lenth), 1);

        q[element].distance = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].lenth);
        __int16_t_clone_array(p[element].distance, q[element].distance, p[element].lenth);

        q[element].intensity = (int16_t*) lcm_malloc(sizeof(int16_t) * q[element].lenth);
        __int16_t_clone_array(p[element].intensity, q[element].intensity, p[element].lenth);

        __float_clone_array(p[element].position, q[element].position, 3);

        __float_clone_array(p[element].vel, q[element].vel, 3);

    }
    return 0;
}

Localization_Msg *Localization_Msg_copy(const Localization_Msg *p)
{
    Localization_Msg *q = (Localization_Msg*) malloc(sizeof(Localization_Msg));
    __Localization_Msg_clone_array(p, q, 1);
    return q;
}

void Localization_Msg_destroy(Localization_Msg *p)
{
    __Localization_Msg_decode_array_cleanup(p, 1);
    free(p);
}

int Localization_Msg_publish(lcm_t *lc, const char *channel, const Localization_Msg *p)
{
      int max_data_size = Localization_Msg_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = Localization_Msg_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _Localization_Msg_subscription_t {
    Localization_Msg_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void Localization_Msg_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    Localization_Msg p;
    memset(&p, 0, sizeof(Localization_Msg));
    status = Localization_Msg_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding Localization_Msg!!!\n", status);
        return;
    }

    Localization_Msg_subscription_t *h = (Localization_Msg_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    Localization_Msg_decode_cleanup (&p);
}

Localization_Msg_subscription_t* Localization_Msg_subscribe (lcm_t *lcm,
                    const char *channel,
                    Localization_Msg_handler_t f, void *userdata)
{
    Localization_Msg_subscription_t *n = (Localization_Msg_subscription_t*)
                       malloc(sizeof(Localization_Msg_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 Localization_Msg_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg Localization_Msg LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int Localization_Msg_subscription_set_queue_capacity (Localization_Msg_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int Localization_Msg_unsubscribe(lcm_t *lcm, Localization_Msg_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe Localization_Msg_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

