/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "FeatureMatchInfoLcm_.h"

static int __FeatureMatchInfoLcm__hash_computed;
static int64_t __FeatureMatchInfoLcm__hash;

int64_t __FeatureMatchInfoLcm__hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __FeatureMatchInfoLcm__get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__FeatureMatchInfoLcm__get_hash };
    (void) cp;

    int64_t hash = 0xa64ee61a0d098382LL
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __FeatureMatchInfoLcm__get_hash(void)
{
    if (!__FeatureMatchInfoLcm__hash_computed) {
        __FeatureMatchInfoLcm__hash = __FeatureMatchInfoLcm__hash_recursive(NULL);
        __FeatureMatchInfoLcm__hash_computed = 1;
    }

    return __FeatureMatchInfoLcm__hash;
}

int __FeatureMatchInfoLcm__encode_array(void *buf, int offset, int maxlen, const FeatureMatchInfoLcm_ *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].type_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].result_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].NewPstfX_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].NewPstfY_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].NewPstfAngle_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].matchRatio_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].matchNum_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfX_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfY_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfAngle_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nPoint_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].Point_, p[element].nPoint_);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nLine_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].Line_, p[element].nLine_);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nPointPair_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].PointPair_, p[element].nPointPair_);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nLinePair_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].LinePair_, p[element].nLinePair_);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int FeatureMatchInfoLcm__encode(void *buf, int offset, int maxlen, const FeatureMatchInfoLcm_ *p)
{
    int pos = 0, thislen;
    int64_t hash = __FeatureMatchInfoLcm__get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __FeatureMatchInfoLcm__encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __FeatureMatchInfoLcm__encoded_array_size(const FeatureMatchInfoLcm_ *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_t_encoded_array_size(&(p[element].type_), 1);

        size += __int32_t_encoded_array_size(&(p[element].result_), 1);

        size += __float_encoded_array_size(&(p[element].NewPstfX_), 1);

        size += __float_encoded_array_size(&(p[element].NewPstfY_), 1);

        size += __float_encoded_array_size(&(p[element].NewPstfAngle_), 1);

        size += __float_encoded_array_size(&(p[element].matchRatio_), 1);

        size += __int32_t_encoded_array_size(&(p[element].matchNum_), 1);

        size += __float_encoded_array_size(&(p[element].InitPstfX_), 1);

        size += __float_encoded_array_size(&(p[element].InitPstfY_), 1);

        size += __float_encoded_array_size(&(p[element].InitPstfAngle_), 1);

        size += __int32_t_encoded_array_size(&(p[element].nPoint_), 1);

        size += __float_encoded_array_size(p[element].Point_, p[element].nPoint_);

        size += __int32_t_encoded_array_size(&(p[element].nLine_), 1);

        size += __float_encoded_array_size(p[element].Line_, p[element].nLine_);

        size += __int32_t_encoded_array_size(&(p[element].nPointPair_), 1);

        size += __float_encoded_array_size(p[element].PointPair_, p[element].nPointPair_);

        size += __int32_t_encoded_array_size(&(p[element].nLinePair_), 1);

        size += __float_encoded_array_size(p[element].LinePair_, p[element].nLinePair_);

    }
    return size;
}

int FeatureMatchInfoLcm__encoded_size(const FeatureMatchInfoLcm_ *p)
{
    return 8 + __FeatureMatchInfoLcm__encoded_array_size(p, 1);
}

int __FeatureMatchInfoLcm__decode_array(const void *buf, int offset, int maxlen, FeatureMatchInfoLcm_ *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].type_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].result_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].NewPstfX_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].NewPstfY_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].NewPstfAngle_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].matchRatio_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].matchNum_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfX_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfY_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfAngle_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nPoint_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].Point_ = (float*) lcm_malloc(sizeof(float) * p[element].nPoint_);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].Point_, p[element].nPoint_);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nLine_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].Line_ = (float*) lcm_malloc(sizeof(float) * p[element].nLine_);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].Line_, p[element].nLine_);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nPointPair_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].PointPair_ = (float*) lcm_malloc(sizeof(float) * p[element].nPointPair_);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].PointPair_, p[element].nPointPair_);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nLinePair_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].LinePair_ = (float*) lcm_malloc(sizeof(float) * p[element].nLinePair_);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].LinePair_, p[element].nLinePair_);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __FeatureMatchInfoLcm__decode_array_cleanup(FeatureMatchInfoLcm_ *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_decode_array_cleanup(&(p[element].type_), 1);

        __int32_t_decode_array_cleanup(&(p[element].result_), 1);

        __float_decode_array_cleanup(&(p[element].NewPstfX_), 1);

        __float_decode_array_cleanup(&(p[element].NewPstfY_), 1);

        __float_decode_array_cleanup(&(p[element].NewPstfAngle_), 1);

        __float_decode_array_cleanup(&(p[element].matchRatio_), 1);

        __int32_t_decode_array_cleanup(&(p[element].matchNum_), 1);

        __float_decode_array_cleanup(&(p[element].InitPstfX_), 1);

        __float_decode_array_cleanup(&(p[element].InitPstfY_), 1);

        __float_decode_array_cleanup(&(p[element].InitPstfAngle_), 1);

        __int32_t_decode_array_cleanup(&(p[element].nPoint_), 1);

        __float_decode_array_cleanup(p[element].Point_, p[element].nPoint_);
        if (p[element].Point_) free(p[element].Point_);

        __int32_t_decode_array_cleanup(&(p[element].nLine_), 1);

        __float_decode_array_cleanup(p[element].Line_, p[element].nLine_);
        if (p[element].Line_) free(p[element].Line_);

        __int32_t_decode_array_cleanup(&(p[element].nPointPair_), 1);

        __float_decode_array_cleanup(p[element].PointPair_, p[element].nPointPair_);
        if (p[element].PointPair_) free(p[element].PointPair_);

        __int32_t_decode_array_cleanup(&(p[element].nLinePair_), 1);

        __float_decode_array_cleanup(p[element].LinePair_, p[element].nLinePair_);
        if (p[element].LinePair_) free(p[element].LinePair_);

    }
    return 0;
}

int FeatureMatchInfoLcm__decode(const void *buf, int offset, int maxlen, FeatureMatchInfoLcm_ *p)
{
    int pos = 0, thislen;
    int64_t hash = __FeatureMatchInfoLcm__get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __FeatureMatchInfoLcm__decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int FeatureMatchInfoLcm__decode_cleanup(FeatureMatchInfoLcm_ *p)
{
    return __FeatureMatchInfoLcm__decode_array_cleanup(p, 1);
}

int __FeatureMatchInfoLcm__clone_array(const FeatureMatchInfoLcm_ *p, FeatureMatchInfoLcm_ *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_clone_array(&(p[element].type_), &(q[element].type_), 1);

        __int32_t_clone_array(&(p[element].result_), &(q[element].result_), 1);

        __float_clone_array(&(p[element].NewPstfX_), &(q[element].NewPstfX_), 1);

        __float_clone_array(&(p[element].NewPstfY_), &(q[element].NewPstfY_), 1);

        __float_clone_array(&(p[element].NewPstfAngle_), &(q[element].NewPstfAngle_), 1);

        __float_clone_array(&(p[element].matchRatio_), &(q[element].matchRatio_), 1);

        __int32_t_clone_array(&(p[element].matchNum_), &(q[element].matchNum_), 1);

        __float_clone_array(&(p[element].InitPstfX_), &(q[element].InitPstfX_), 1);

        __float_clone_array(&(p[element].InitPstfY_), &(q[element].InitPstfY_), 1);

        __float_clone_array(&(p[element].InitPstfAngle_), &(q[element].InitPstfAngle_), 1);

        __int32_t_clone_array(&(p[element].nPoint_), &(q[element].nPoint_), 1);

        q[element].Point_ = (float*) lcm_malloc(sizeof(float) * q[element].nPoint_);
        __float_clone_array(p[element].Point_, q[element].Point_, p[element].nPoint_);

        __int32_t_clone_array(&(p[element].nLine_), &(q[element].nLine_), 1);

        q[element].Line_ = (float*) lcm_malloc(sizeof(float) * q[element].nLine_);
        __float_clone_array(p[element].Line_, q[element].Line_, p[element].nLine_);

        __int32_t_clone_array(&(p[element].nPointPair_), &(q[element].nPointPair_), 1);

        q[element].PointPair_ = (float*) lcm_malloc(sizeof(float) * q[element].nPointPair_);
        __float_clone_array(p[element].PointPair_, q[element].PointPair_, p[element].nPointPair_);

        __int32_t_clone_array(&(p[element].nLinePair_), &(q[element].nLinePair_), 1);

        q[element].LinePair_ = (float*) lcm_malloc(sizeof(float) * q[element].nLinePair_);
        __float_clone_array(p[element].LinePair_, q[element].LinePair_, p[element].nLinePair_);

    }
    return 0;
}

FeatureMatchInfoLcm_ *FeatureMatchInfoLcm__copy(const FeatureMatchInfoLcm_ *p)
{
    FeatureMatchInfoLcm_ *q = (FeatureMatchInfoLcm_*) malloc(sizeof(FeatureMatchInfoLcm_));
    __FeatureMatchInfoLcm__clone_array(p, q, 1);
    return q;
}

void FeatureMatchInfoLcm__destroy(FeatureMatchInfoLcm_ *p)
{
    __FeatureMatchInfoLcm__decode_array_cleanup(p, 1);
    free(p);
}

int FeatureMatchInfoLcm__publish(lcm_t *lc, const char *channel, const FeatureMatchInfoLcm_ *p)
{
      int max_data_size = FeatureMatchInfoLcm__encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = FeatureMatchInfoLcm__encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _FeatureMatchInfoLcm__subscription_t {
    FeatureMatchInfoLcm__handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void FeatureMatchInfoLcm__handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    FeatureMatchInfoLcm_ p;
    memset(&p, 0, sizeof(FeatureMatchInfoLcm_));
    status = FeatureMatchInfoLcm__decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding FeatureMatchInfoLcm_!!!\n", status);
        return;
    }

    FeatureMatchInfoLcm__subscription_t *h = (FeatureMatchInfoLcm__subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    FeatureMatchInfoLcm__decode_cleanup (&p);
}

FeatureMatchInfoLcm__subscription_t* FeatureMatchInfoLcm__subscribe (lcm_t *lcm,
                    const char *channel,
                    FeatureMatchInfoLcm__handler_t f, void *userdata)
{
    FeatureMatchInfoLcm__subscription_t *n = (FeatureMatchInfoLcm__subscription_t*)
                       malloc(sizeof(FeatureMatchInfoLcm__subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 FeatureMatchInfoLcm__handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg FeatureMatchInfoLcm_ LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int FeatureMatchInfoLcm__subscription_set_queue_capacity (FeatureMatchInfoLcm__subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int FeatureMatchInfoLcm__unsubscribe(lcm_t *lcm, FeatureMatchInfoLcm__subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe FeatureMatchInfoLcm__handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

