/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "LcmCloudAdjusted.h"

static int __LcmCloudAdjusted_hash_computed;
static int64_t __LcmCloudAdjusted_hash;

int64_t __LcmCloudAdjusted_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __LcmCloudAdjusted_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__LcmCloudAdjusted_get_hash };
    (void) cp;

    int64_t hash = 0x9791b9f19ec7aa70LL
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __LcmCloudAdjusted_get_hash(void)
{
    if (!__LcmCloudAdjusted_hash_computed) {
        __LcmCloudAdjusted_hash = __LcmCloudAdjusted_hash_recursive(NULL);
        __LcmCloudAdjusted_hash_computed = 1;
    }

    return __LcmCloudAdjusted_hash;
}

int __LcmCloudAdjusted_encode_array(void *buf, int offset, int maxlen, const LcmCloudAdjusted *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nSize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].ptX_, p[element].nSize);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].ptY_, p[element].nSize);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].nIntensitySize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, p[element].Intensity_, p[element].nIntensitySize);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfX_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfY_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfAngle_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int LcmCloudAdjusted_encode(void *buf, int offset, int maxlen, const LcmCloudAdjusted *p)
{
    int pos = 0, thislen;
    int64_t hash = __LcmCloudAdjusted_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __LcmCloudAdjusted_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __LcmCloudAdjusted_encoded_array_size(const LcmCloudAdjusted *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_t_encoded_array_size(&(p[element].nSize), 1);

        size += __float_encoded_array_size(p[element].ptX_, p[element].nSize);

        size += __float_encoded_array_size(p[element].ptY_, p[element].nSize);

        size += __int32_t_encoded_array_size(&(p[element].nIntensitySize), 1);

        size += __int32_t_encoded_array_size(p[element].Intensity_, p[element].nIntensitySize);

        size += __float_encoded_array_size(&(p[element].InitPstfX_), 1);

        size += __float_encoded_array_size(&(p[element].InitPstfY_), 1);

        size += __float_encoded_array_size(&(p[element].InitPstfAngle_), 1);

    }
    return size;
}

int LcmCloudAdjusted_encoded_size(const LcmCloudAdjusted *p)
{
    return 8 + __LcmCloudAdjusted_encoded_array_size(p, 1);
}

int __LcmCloudAdjusted_decode_array(const void *buf, int offset, int maxlen, LcmCloudAdjusted *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nSize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ptX_ = (float*) lcm_malloc(sizeof(float) * p[element].nSize);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].ptX_, p[element].nSize);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].ptY_ = (float*) lcm_malloc(sizeof(float) * p[element].nSize);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].ptY_, p[element].nSize);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].nIntensitySize), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].Intensity_ = (int32_t*) lcm_malloc(sizeof(int32_t) * p[element].nIntensitySize);
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, p[element].Intensity_, p[element].nIntensitySize);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfX_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfY_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].InitPstfAngle_), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __LcmCloudAdjusted_decode_array_cleanup(LcmCloudAdjusted *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_decode_array_cleanup(&(p[element].nSize), 1);

        __float_decode_array_cleanup(p[element].ptX_, p[element].nSize);
        if (p[element].ptX_) free(p[element].ptX_);

        __float_decode_array_cleanup(p[element].ptY_, p[element].nSize);
        if (p[element].ptY_) free(p[element].ptY_);

        __int32_t_decode_array_cleanup(&(p[element].nIntensitySize), 1);

        __int32_t_decode_array_cleanup(p[element].Intensity_, p[element].nIntensitySize);
        if (p[element].Intensity_) free(p[element].Intensity_);

        __float_decode_array_cleanup(&(p[element].InitPstfX_), 1);

        __float_decode_array_cleanup(&(p[element].InitPstfY_), 1);

        __float_decode_array_cleanup(&(p[element].InitPstfAngle_), 1);

    }
    return 0;
}

int LcmCloudAdjusted_decode(const void *buf, int offset, int maxlen, LcmCloudAdjusted *p)
{
    int pos = 0, thislen;
    int64_t hash = __LcmCloudAdjusted_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __LcmCloudAdjusted_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int LcmCloudAdjusted_decode_cleanup(LcmCloudAdjusted *p)
{
    return __LcmCloudAdjusted_decode_array_cleanup(p, 1);
}

int __LcmCloudAdjusted_clone_array(const LcmCloudAdjusted *p, LcmCloudAdjusted *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_t_clone_array(&(p[element].nSize), &(q[element].nSize), 1);

        q[element].ptX_ = (float*) lcm_malloc(sizeof(float) * q[element].nSize);
        __float_clone_array(p[element].ptX_, q[element].ptX_, p[element].nSize);

        q[element].ptY_ = (float*) lcm_malloc(sizeof(float) * q[element].nSize);
        __float_clone_array(p[element].ptY_, q[element].ptY_, p[element].nSize);

        __int32_t_clone_array(&(p[element].nIntensitySize), &(q[element].nIntensitySize), 1);

        q[element].Intensity_ = (int32_t*) lcm_malloc(sizeof(int32_t) * q[element].nIntensitySize);
        __int32_t_clone_array(p[element].Intensity_, q[element].Intensity_, p[element].nIntensitySize);

        __float_clone_array(&(p[element].InitPstfX_), &(q[element].InitPstfX_), 1);

        __float_clone_array(&(p[element].InitPstfY_), &(q[element].InitPstfY_), 1);

        __float_clone_array(&(p[element].InitPstfAngle_), &(q[element].InitPstfAngle_), 1);

    }
    return 0;
}

LcmCloudAdjusted *LcmCloudAdjusted_copy(const LcmCloudAdjusted *p)
{
    LcmCloudAdjusted *q = (LcmCloudAdjusted*) malloc(sizeof(LcmCloudAdjusted));
    __LcmCloudAdjusted_clone_array(p, q, 1);
    return q;
}

void LcmCloudAdjusted_destroy(LcmCloudAdjusted *p)
{
    __LcmCloudAdjusted_decode_array_cleanup(p, 1);
    free(p);
}

int LcmCloudAdjusted_publish(lcm_t *lc, const char *channel, const LcmCloudAdjusted *p)
{
      int max_data_size = LcmCloudAdjusted_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = LcmCloudAdjusted_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _LcmCloudAdjusted_subscription_t {
    LcmCloudAdjusted_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void LcmCloudAdjusted_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    LcmCloudAdjusted p;
    memset(&p, 0, sizeof(LcmCloudAdjusted));
    status = LcmCloudAdjusted_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding LcmCloudAdjusted!!!\n", status);
        return;
    }

    LcmCloudAdjusted_subscription_t *h = (LcmCloudAdjusted_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    LcmCloudAdjusted_decode_cleanup (&p);
}

LcmCloudAdjusted_subscription_t* LcmCloudAdjusted_subscribe (lcm_t *lcm,
                    const char *channel,
                    LcmCloudAdjusted_handler_t f, void *userdata)
{
    LcmCloudAdjusted_subscription_t *n = (LcmCloudAdjusted_subscription_t*)
                       malloc(sizeof(LcmCloudAdjusted_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 LcmCloudAdjusted_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg LcmCloudAdjusted LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int LcmCloudAdjusted_subscription_set_queue_capacity (LcmCloudAdjusted_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int LcmCloudAdjusted_unsubscribe(lcm_t *lcm, LcmCloudAdjusted_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe LcmCloudAdjusted_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

